variables:
    GIT_STRATEGY: clone

test-linux-ubuntu-clang50:
    stage: test
    tags:
      - linux
      - docker
    image: geordiejones/cpp14-build-machine
    script: ./ci.sh

test-linux-ubuntu-gcc5:
    stage: test
    tags:
      - linux
      - docker
    image: lasote/conangcc5
    script: ./ci.sh
