variables:
    GIT_STRATEGY: clone
    CROSS_BUILDING: "NO"

test-x86-linux-ubuntu-clang50:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:clang50-x86
    script: ./ci.sh

test-x86-linux-ubuntu-gcc5:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc5-x86
    script: ./ci.sh

test-x86-linux-ubuntu-gcc6:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc6-x86
    script: ./ci.sh

test-x86-linux-ubuntu-gcc7:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc7-x86
    script: ./ci.sh

test-armv7-linux-gcc5:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc5-armv7
    variables:
        CROSS_BUILDING: "YES"
    script: ./ci.sh
    allow_failure: true # TODO: Enable build. See https://github.com/foonathan/type_safe/issues/78

test-armv7-linux-gcc6:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc6-armv7
    variables:
        CROSS_BUILDING: "YES"
    script: ./ci.sh

test-armv7-linux-gcc7:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc7-armv7
    variables:
        CROSS_BUILDING: "YES"
    script: ./ci.sh

test-x86-windows-msvc2017:
  stage: build
  tags:
    - vs2017
    - windows
  before_script:
    - set PATH=%PATH%;C:\Qt\5.10.0\msvc2017_64\bin
  script:
    - mkdir build
    - cd build
    - '"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64" -DTINYREFL_BUILD_EXAMPLES=ON -DTINYREFL_BUILD_TESTS=ON'
    - '"C:\Program Files\CMake\bin\cmake.exe" ..'
    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target ALL_BUILD'
    - '"C:\Program Files\CMake\bin\ctest.exe" . -V'
