variables:
    GIT_STRATEGY: clone

test-linux-ubuntu-clang50:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:clang50
    script: ./ci.sh

test-linux-ubuntu-gcc5:
    stage: test
    tags:
      - linux
      - docker
    image: manu343726/tinyrefl:gcc5
    script: ./ci.sh
