test-linux-ubuntu-clang50:
    stage: test
    tags:
      - linux
      - docker
    image: geordiejones/cpp14-build-machine
    script: ./ci.sh

test-linux-ubuntu-gcc49:
    stage: test
    tags:
      - linux
      - docker
    image: lasote/conangcc49
    script: ./ci.sh
